#!/usr/bin/env python

# SPDX-FileCopyrightText: 2021 Forschungs- und Entwicklungszentrum Fachhochschule Kiel GmbH
#
# SPDX-License-Identifier: CC0-1.0

import os

import serial.tools.list_ports


devices = serial.tools.list_ports.comports()
match = next(
    elem
    for elem in devices
    if elem.serial_number == os.environ["PYLAB_USB_SERIAL_NUMBER_DEVICE"]
)

with open("platformio.ini.in", "r") as f:
    platformio = f.read()

platformio = platformio.replace("@UPLOAD_PORT", match.device)

with open("platformio.ini", "w") as f:
    f.write(platformio)
