#!/usr/bin/env python

# SPDX-FileCopyrightText: 2021 Forschungs- und Entwicklungszentrum Fachhochschule Kiel GmbH
#
# SPDX-License-Identifier: CC0-1.0

import os


with open("requirements.txt.in", "r") as f:
    requirements = f.read()

requirements = requirements.replace("${GITHUB_TOKEN}", os.environ["GITHUB_TOKEN"])

with open("requirements.txt", "w") as f:
    f.write(requirements)
