# SPDX-FileCopyrightText: 2021 Forschungs- und Entwicklungszentrum Fachhochschule Kiel GmbH
# 
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI (install, test)
on:
  push:
    branches: master
  pull_request:
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.MALTE_RND_SSH }}
    - name: Install requirements
      run: |
        ./freeze
        pip install -r requirements.txt
        pip install .
      env:
        PYLAB_GITHUB_ACCESS: git+https://${{ secrets.MALTE_RND_ACCESS_TOKEN }}
    - name: Setup virtual CAN
      run: |
        sudo apt-get install -y linux-modules-extra-$(uname -r)  # See https://github.com/linux-can/can-utils/issues/46
        sudo modprobe vcan
        sudo modprobe can-gw
        sudo apt-get install can-utils
        sudo ip link add dev vcan0 type vcan
        sudo ip link add dev vcan1 type vcan
        sudo ip link add dev vcan2 type vcan
        sudo ip link set up vcan0
        sudo ip link set up vcan1
        sudo ip link set up vcan2
        sudo cangw -A -s vcan0 -d vcan1 -e
        sudo cangw -A -s vcan1 -d vcan2 -e
    - name: Run tests
      run: |
        pytest -vv tests/core
        pytest -vv tests/tools
        pytest -vv tests/test_pylab_cli.py
        pytest -vv tests/live/test_live.py
        pytest -vv tests/live/plugin/modbus
        pytest -vv tests/_private
        pytest -vv tests/live/plugin/can
